name: Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM
        run: |
          sudo apt-get update && sudo apt-get install -y llvm-9-dev
          sudo update-alternatives --verbose \
            --install /usr/bin/llvm-config       llvm-config      /usr/bin/llvm-config-9 100 \
            --slave   /usr/bin/llvm-ar           llvm-ar          /usr/bin/llvm-ar-9 \
            --slave   /usr/bin/llvm-as           llvm-as          /usr/bin/llvm-as-9 \
            --slave   /usr/bin/llvm-bcanalyzer   llvm-bcanalyzer  /usr/bin/llvm-bcanalyzer-9 \
            --slave   /usr/bin/llvm-cov          llvm-cov         /usr/bin/llvm-cov-9 \
            --slave   /usr/bin/llvm-diff         llvm-diff        /usr/bin/llvm-diff-9 \
            --slave   /usr/bin/llvm-dis          llvm-dis         /usr/bin/llvm-dis-9 \
            --slave   /usr/bin/llvm-dwarfdump    llvm-dwarfdump   /usr/bin/llvm-dwarfdump-9 \
            --slave   /usr/bin/llvm-extract      llvm-extract     /usr/bin/llvm-extract-9 \
            --slave   /usr/bin/llvm-link         llvm-link        /usr/bin/llvm-link-9 \
            --slave   /usr/bin/llvm-mc           llvm-mc          /usr/bin/llvm-mc-9 \
            --slave   /usr/bin/llvm-nm           llvm-nm          /usr/bin/llvm-nm-9 \
            --slave   /usr/bin/llvm-objdump      llvm-objdump     /usr/bin/llvm-objdump-9 \
            --slave   /usr/bin/llvm-ranlib       llvm-ranlib      /usr/bin/llvm-ranlib-9 \
            --slave   /usr/bin/llvm-readobj      llvm-readobj     /usr/bin/llvm-readobj-9 \
            --slave   /usr/bin/llvm-rtdyld       llvm-rtdyld      /usr/bin/llvm-rtdyld-9 \
            --slave   /usr/bin/llvm-size         llvm-size        /usr/bin/llvm-size-9 \
            --slave   /usr/bin/llvm-stress       llvm-stress      /usr/bin/llvm-stress-9 \
            --slave   /usr/bin/llvm-symbolizer   llvm-symbolizer  /usr/bin/llvm-symbolizer-9 \
            --slave   /usr/bin/llvm-tblgen       llvm-tblgen      /usr/bin/llvm-tblgen-9
          llvm-config --version
          llvm-config --version | grep -q "^9.0.1$"

      - name: Cache stack packages
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ hashFiles('stack.yaml') }}

      - name: Build and run tests
        shell: bash
        run: |
          set -ex
          stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack test --fast --no-terminal
          python3 tests.py
